package com.genspark.Entity;

import jakarta.persistence.*;

@Entity//Entity allows us to generate a table for the database
@Table(name="tbl_courses")
public class Course {

    @Id
    @Column(name="c_id")
    @GeneratedValue(strategy = GenerationType.AUTO)
    private int courseid;
    private String title;
    private String instructor;

    public Course(){

    }

    /**
     *
     * @param title
     * @param instructor
     *
     * Because courseid is autogenerated, we remove it from the constructor
     */
    public Course( String title, String instructor) {
        this.title = title;
        this.instructor = instructor;
    }
    public int getCourseid() {
        return courseid;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getInstructor() {
        return instructor;
    }

    public void setInstructor(String instructor) {
        this.instructor = instructor;
    }


}
